
version: "1.0"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  nestjs-api:
    ports:
      - "3000:3000"
    build: .
    depends_on:
    - redis
    environment:
    - REDIS_HOST=redis